#pragma once

#define PIN_DISP_DATA0		GPIO_NUM_45
#define PIN_DISP_DATA1		GPIO_NUM_48
#define PIN_DISP_DATA2		GPIO_NUM_47
#define PIN_DISP_DATA3		GPIO_NUM_21
#define PIN_DISP_DATA4		GPIO_NUM_14
#define PIN_DISP_DATA5		GPIO_NUM_13
#define PIN_DISP_DATA6		GPIO_NUM_12
#define PIN_DISP_DATA7		GPIO_NUM_11
#define PIN_DISP_PCLK 		GPIO_NUM_36
#define PIN_DISP_CS			GPIO_NUM_38
#define PIN_DISP_DC			GPIO_NUM_37
#define PIN_DISP_RST		GPIO_NUM_35
#define PIN_DISP_BACKLIGHT	GPIO_NUM_46

#define PIN_I2C_SDA			GPIO_NUM_4
#define PIN_I2C_SCL			GPIO_NUM_5
#define PIN_I2C_RESET		GPIO_NUM_6

#define PIN_GPIO_A			GPIO_NUM_40
#define PIN_GPIO_B			GPIO_NUM_39
#define PIN_GPIO_START		GPIO_NUM_16
#define PIN_GPIO_UP			GPIO_NUM_15
#define PIN_GPIO_DOWN		GPIO_NUM_18
#define PIN_GPIO_LEFT		GPIO_NUM_17
#define PIN_GPIO_RIGHT		GPIO_NUM_8

#define PIN_AUDIO_SDI1		GPIO_NUM_3	// = DOUT
#define	PIN_AUDIO_LRCK1		GPIO_NUM_41	// = WS
#define PIN_AUDIO_SCK1		GPIO_NUM_42	// = BCLK
